/**
 * Parses the extracted text of an electronically-filed House Periodic
 * Transaction Report into normalized trade records.
 *
 * Electronic PTRs are generated by the Clerk's eFiling system, so rows
 * follow a fixed shape inside the text stream:
 *
 *   <Asset Name> (TICKER) [ST] P|S|E (partial)? MM/DD/YYYY MM/DD/YYYY $1,001 - $15,000
 *
 * Anything that doesn't match (options descriptions, footnotes, the
 * repeated Description blocks) is ignored rather than guessed at.
 */

import type {
  CongressionalFiling,
  CongressionalTrade,
  CongressionalTradeAction,
} from './congressionalTrades.types';

const TRADE_ROW =
  /\(([A-Z][A-Z.\/-]{0,9})\)\s*\[[A-Z]{2}\]\s*([PSE])\s*(\(partial\))?\s*(\d{2}\/\d{2}\/\d{4})\s*(\d{2}\/\d{2}\/\d{4})\s*\$([\d,]+)\s*-\s*\$?([\d,]+)/g;

const ACTIONS: Record<string, CongressionalTradeAction> = {
  P: 'buy',
  S: 'sell',
  E: 'exchange',
};

function toIsoDate(usDate: string): string {
  const [m, d, y] = usDate.split('/');
  return `${y}-${m}-${d}`;
}

function parseAmount(raw: string): number {
  return parseInt(raw.replace(/,/g, ''), 10) || 0;
}

/**
 * Recovers the asset name from the text immediately before the ticker.
 * Walks back from the match to the previous row boundary and strips
 * table-header debris.
 */
function extractAssetName(text: string, matchStart: number, prevEnd: number): string {
  const windowStart = Math.max(prevEnd, matchStart - 120);
  let candidate = text.slice(windowStart, matchStart);
  // Drop everything before the last sentence-ish boundary left by the
  // previous row's description/footer text.
  candidate = candidate.split(/(?:\$[\d,.]+\/share|>\s*\$200\?|F\s+S: New|D:\s)/).pop() ?? candidate;
  return candidate.replace(/\s+/g, ' ').replace(/^[^A-Za-z]+/, '').trim();
}

export function parsePtrText(filing: CongressionalFiling, text: string): CongressionalTrade[] {
  const trades: CongressionalTrade[] = [];
  const seen = new Set<string>();
  let prevEnd = 0;
  let match: RegExpExecArray | null;

  TRADE_ROW.lastIndex = 0;
  while ((match = TRADE_ROW.exec(text)) !== null) {
    const [full, ticker, actionCode, partial, txDate, notifDate, minRaw, maxRaw] = match;
    const action = ACTIONS[actionCode];
    if (!action) continue;

    const isoTxDate = toIsoDate(txDate);
    // One filing can list the same ticker on multiple rows (different lots);
    // keep them, but collapse exact duplicates caused by repeated
    // Description blocks re-matching.
    const dedupeKey = `${ticker}:${actionCode}:${isoTxDate}:${minRaw}:${match.index}`;
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);

    trades.push({
      id: `${filing.docId}:${ticker}:${trades.length}`,
      docId: filing.docId,
      politician: filing.politician,
      stateDistrict: filing.stateDistrict,
      chamber: filing.chamber,
      ticker: ticker.replace('/', '.'), // BRK/B -> BRK.B, matches market data notation
      assetName: extractAssetName(text, match.index, prevEnd),
      action,
      partial: Boolean(partial),
      transactionDate: isoTxDate,
      notificationDate: toIsoDate(notifDate),
      filingDate: filing.filingDate,
      amountMin: parseAmount(minRaw),
      amountMax: parseAmount(maxRaw),
      pdfUrl: filing.pdfUrl,
    });

    prevEnd = match.index + full.length;
  }

  return trades;
}
