-- =============================================================================
-- REFERENCE ONLY — NOT AN EXECUTABLE MIGRATION
-- =============================================================================
-- These foundation tables were created manually in Supabase before migrations
-- were tracked in source control. This file documents what exists so the schema
-- can be reconstructed from scratch if needed.
--
-- Tables 005+ have real migration files. This covers everything before that.
-- =============================================================================

-- Core research engine tables (created pre-migration tracking)
--   research_runs              — one row per daily/weekly research execution
--   market_snapshots           — point-in-time market data captured per run
--   prediction_candidates      — scored predictions generated by the engine
--   prediction_inputs          — data sources that fed each prediction
--   prediction_outcomes        — actual results after prediction window closes
--   prediction_signal_observations — per-signal values recorded at prediction time

-- Scoring & learning tables
--   research_scoring_weights   — base weights for each scoring bucket
--   scoring_weight_overrides   — adaptive weight adjustments from learning engine
--   research_signal_performance — accuracy stats per signal type
--   learning_insights          — AI-generated lessons from outcome analysis
--   learning_reports           — periodic learning summary reports

-- Watchlist tables
--   watchlist_items            — dynamic watchlist with status tracking
--   watchlist_change_log       — audit trail of watchlist additions/removals
--   watchlist_candidates       — scored candidates from universe discovery

-- Research signals
--   research_signals           — external signals (congress trades, etc.)

-- Tables created by numbered migrations (005+):
--   005: paper_option_candidates, paper_option_outcomes
--   006: option_learning_stats
--   007: paper_stock_candidates, paper_stock_outcomes, stock_learning_stats
--   013: candidate_generation_audit
